# Generated by Django 5.0.4 on 2024-04-15 12:17

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.users'),
            preserve_default=False,
        ),
    ]
